### ISSUE TITLE
BUG: the names of DataFrame logicalSources are interpreted as files when they have file extension

### ISSUE THREAD

**Issue by ershimen** [TheRazorace/morph-kgc-ram#1]
####  What Happens?

In this code:

```
import pandas as pd
import morph_kgc

users_df = pd.DataFrame({'Id': [1,2,3,4],\
                      'Username': ["@jude","@emily","@wayne","@jordan1"], \
                      'Name': ["Jude", "Emily", "Wayne", "Jordan"],\
                      'Surname': ["White", "Van de Beeck", "Peterson", "Stones"]})
followers_df = pd.DataFrame({'Id': [1,2,3,4],\
                      'Followers': [344, 456, 1221, 23]})

data_dict = {"variable1.csv": users_df,
            "variable2.csv": followers_df}

config = """[DataSource]
mappings=./mapping_rml.ttl
"""

g_rdflib = morph_kgc.materialize(config, data_dict)
```

when the keys of `data_dict` have file extension (for example ".csv") they are interpreted as files instead of keys of the dictionary. The mapping engine should read the information stored in the DataFrame, but it tries to read the files "variable1.csv" and "variable2.csv". It seems like this behavior happens with other file extensions.

#### To Reproduce

1. Download this mapping: 

[https://github.com/morph-kgc/morph-kgc/blob/main/examples/dataframe/mapping_rml.ttl](https://github.com/morph-kgc/morph-kgc/blob/main/examples/dataframe/mapping_rml.ttl)

2. Change "variable1" to "variable1.csv" and "variable2" to  "variable2.csv" in the mapping file.
3. Run the mentioned code.
4. The error is `FileNotFoundError: [Errno 2] No such file or directory: 'variable2.csv'`

To make the code work as expected, remove ".csv" from both the mapping file and the mentioned code.

#### Environment:
 - OS: Windows 10
 - Python version: 3.9
 - Morph-KGC version: 2.5.1

**Comment by TheRazorace** [comment]
Closed in latest update! Thank you for your help!
